service: movie-log-graph-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  stage: dev

functions:
  app:
    handler: .build/serverless.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
